### ISSUE TITLE
how to check for detections

### ISSUE THREAD

**Issue by backslashxx** [bindhosts/bindhosts#4]
![Image](https://github.com/user-attachments/assets/064c637a-bb7a-4d4b-8320-0be333ca0263)

These two detectors has verbose description  if your hosts file is being detected as modified.

Do keep in mind that the only detections we care about here are:

"Hosts File Modified" and a "/data/adb/modules/bindhosts/system/etc" mount.
If you have other detections, it likely is NOT our problem.

You can get them here
https://github.com/reveny/Android-Native-Root-Detector/releases
https://github.com/RabehX/Securify/releases

**Comment by kekkodance** [comment]
how does one avoid the Hosts File size from being detected? every mode makes native detector complain

**Comment by ahmad24shargh** [comment]
There was no detection until version 2.0.5 (mode 1) but version 2.0.6 sets the mode to 2 and forcing the mode change does not change anything (any mode)
Only zn-hostsredirect can hide the detection.
...
Downgrading to version 2.0.5 fixed the problem

ksun 12800 (manager & driver)
susfs 1.5.9
redmi note 12
android13-5.15

**Comment by selfmusing** [comment]
> how does one avoid the Hosts File size from being detected? every mode makes native detector complain

send a screenshot of your modules & which root method do you use ?

**Comment by zxsleebu** [comment]
for me it's getting detected in the same way as @DarkAngel117

**Comment by messipenguin** [comment]
<img width="1280" height="2772" alt="Image" src="https://github.com/user-attachments/assets/b62cea17-5a5c-40c8-b6be-b5392969f2b6" />

Same as above, detected modified hosts file when paired with bindhosts_213-99151b8.zip
